version: "3.1"

services:
  pingdirectory:
    image: pingidentity/pingdirectory:2007-alpine-8.1.0.0
    environment:
      - SERVER_PROFILE_URL=https://github.com/tarunmadiraju/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - PING_IDENTITY_ACCEPT_EULA=YES
      - PING_IDENTITY_DEVOPS_USER=tarunmadiraju@pingidentity.com
      - PING_IDENTITY_DEVOPS_KEY=3a6cdf55-89d7-4cd2-9ece-c8c0131957b1

        #volumes:
        #  - ./pingdirectory-out:/opt/out

    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
                    
  pingdataconsole:
    image: pingidentity/pingdataconsole:latest
    ports:
      - 8443:8443
    networks:
      - pingnet


  pingfederate:
    image: pingidentity/pingfederate:10.3.2-edge
    #command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/tarunmadiraju/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingfederate
      - PING_IDENTITY_ACCEPT_EULA=YES
      - PING_IDENTITY_DEVOPS_USER=tarunmadiraju@pingidentity.com
      - PING_IDENTITY_DEVOPS_KEY=3a6cdf55-89d7-4cd2-9ece-c8c0131957b1

    extra_hosts:
      - "EC2AMAZ-2MNFVU0.tarun.lab:10.101.19.236"


    ports:
      - 9031:9031
      - 9999:9999

    networks:
      - pingnet

  pingaccess:
    image: pingidentity/pingaccess:latest
    #command: wait-for pingfederate:9031 -t 820 -- entrypoint.sh start-server
    command: entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/tarunmadiraju/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingaccess
      - OPERATIONAL_MODE=STANDALONE
      - level=DEBUG
      - PA_CONSOLE_HOST=pingaccess
      - INITIAL_ADMIN_PASSWORD=2FederateM0re
      - PING_IDENTITY_ACCEPT_EULA=YES
      - PING_IDENTITY_DEVOPS_USER=tarunmadiraju@pingidentity.com
      - PING_IDENTITY_DEVOPS_KEY=3a6cdf55-89d7-4cd2-9ece-c8c0131957b1

    ports:
      - 443:3000
      - 9000:9000
    networks:
      - pingnet
        
  pingdatagovernance:
    image: pingidentity/pingdatagovernance:latest
    env_file:
      - ~/.pingidentity/devops
    command: wait-for pingfederate:9031 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/tarunmadiraju/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdatagovernance
      - PING_IDENTITY_ACCEPT_EULA=YES
      - PING_IDENTITY_DEVOPS_USER=tarunmadiraju@pingidentity.com
      - PING_IDENTITY_DEVOPS_KEY=3a6cdf55-89d7-4cd2-9ece-c8c0131957b1
    env_file:
      - ~/.pingidentity/devops
    ports:
      - 2443:443
    networks:
      - pingnet

  pingcentral:
    image:  pingidentity/1.7.0-latest
    #command: wait-for pingcentral-db:3306 -t 7200 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingcentral/external-mysql-db
      - PING_CENTRAL_BLIND_TRUST=true
      - PING_CENTRAL_VERIFY_HOSTNAME=false
      - PING_IDENTITY_ACCEPT_EULA=YES  
      - MYSQL_SERVICE_HOST=pingcentral-db
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_DATABASE=pingcentral
      - MYSQL_USER=root
      - MYSQL_PASSWORD=2Federate
    env_file:
      - ~/.pingidentity/devops
    ports:
      - "9022:9022"
    depends_on:
      - "pingcentral-db"
    networks:
      - pingnet

  pingcentral-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 2Federate
    ports:
      - "3306:3306"
    networks:
      - pingnet

networks:
    pingnet:
