#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at
# trunk/unboundid/resource/legal-notices/cddl.txt
# or http://www.opensource.org/licenses/cddl1.php.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at
# trunk/unboundid/resource/legal-notices/cddl.txt.  If applicable,
# add the following below this CDDL HEADER, with the fields enclosed
# by brackets "[]" replaced with your own identifying information:
#      Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
#      Portions Copyright 2007-2020 Ping Identity Corporation
#      Portions Copyright 2006-2008 Sun Microsystems, Inc.


# Capture the current working directory so that we can change to it later.
# Then capture the location of this script and the server instance
# root so that we can use them to create appropriate paths.
WORKING_DIR=`pwd`

cd "`dirname "${0}"`"
SCRIPT_DIR=`pwd`

INSTANCE_ROOT=${SCRIPT_DIR}
export INSTANCE_ROOT

SCRIPT_NAME=setup
export SCRIPT_NAME

# Since the server may be distributed without the JE jar file, make sure that
# it exists before continuing.  If it cannot be found, then instruct the user
# to download and install it.  Note that since the file name may vary, then
# we have to use a slightly awkward way of checking to see if it's there.
if test -f "${INSTANCE_ROOT}/lib/_require-je.sh"
then
  . "${INSTANCE_ROOT}/lib/_require-je.sh"
  if test ${MISSING_JE} -eq 1
  then
    exit 1
  fi
fi

cd "${WORKING_DIR}"

# Setup checks for the availability of system tools for collect-support-data so use the same path.
UNBOUNDID_PATH_OVERRIDE=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/java/bin:/usr/sfw/bin
export UNBOUNDID_PATH_OVERRIDE

# Set environment variables
SCRIPT_UTIL_CMD=set-full-environment-and-test-java
export SCRIPT_UTIL_CMD
.  "${INSTANCE_ROOT}/lib/_script-util.sh"
RETURN_CODE=$?
if test ${RETURN_CODE} -ne 0
then
  exit ${RETURN_CODE}
fi

# Launch the setup process.
"${PRIVATE_UNBOUNDID_JAVA_BIN}" ${PRIVATE_UNBOUNDID_JAVA_ARGS} ${SCRIPT_NAME_ARG} com.unboundid.quicksetup.installer.SetupLauncher "${@}"

# return part
RETURN_CODE=$?
if test ${RETURN_CODE} -eq 50
then
  # Version info was on requested
  exit 0
else
  exit ${RETURN_CODE}
fi
